services:
  mongodb:
    container_name: mongodb_container
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes: 
      - ./docker-volumes/data:/data/db

  app:
    container_name: app_container
    build: .
    restart: always
    depends_on:
      - mongodb
    ports:
      - 5000:5000
    env_file: .env
    volumes:
      - ./:/app